### ISSUE TITLE
headView内控件点击事件问题

### ISSUE THREAD

**Issue by taoranziwangji** [YvesCheung/TouchEventBus#6]
headView内的view如果设置了点击事件的话，那么在滑动时如果手指在view处抬起会触发view的点击事件，这个需要怎么解决呢？

**Comment by YvesCheung** [comment]
谢谢你发现了这个Bug。已修复： 1b418facede596d5ddcef5cb28567b1529ba4694
准备在1.5.3中发布这个修改。
