### ISSUE TITLE
recyclerview包裹SmartRefreshLayout冲突

### ISSUE THREAD

**Issue by taoranziwangji** [YvesCheung/TouchEventBus#8]
recyclerView如果外面也包裹一层SmartRefreshLayout的话（只要上拉加载功能），向下滑动列表fling时会出现冲突，即列表没到头header却滚动了的情况

**Comment by YvesCheung** [comment]
谢谢你发现了这个Bug。

先说说问题的原因：
在向下fling时，RecyclerView无论能否滑动都会把fling事件吃掉（consumed==true)。所以我没有使用 consumed字段来判断是否要fling，而是使用了 View.canScrollVertical 来判断，如果子View无法 canScrollVertical时，就可以对自己进行fling。
这种判断方法对RecyclerView是有效的，但是对 SmartRefreshLayout就无效了，所以出现这个Bug。

解决问题有两种办法：
1. 重写 SmartRefreshLayout，并完善它的 View#canScrollVertical 方法。这种方案比较麻烦。
2. 本库使用consumed字段来判断fling。并重写 RecyclerView 对consumed的判断。

目前Demo已经用第二种解决方案修复了这个问题。 7b5d362b90e74bede0d0b9588e10a537a41d4614 
你可以：
1. 把本库的版本升到 1.6.0 
2. 然后像demo那样重写 RecyclerView，并修复RecyclerView的fling问题

**Comment by YvesCheung** [comment]
1.7.0开始把fling动作替换成TYPE_NON_TOUCH的NestedScrolling。根本上解决这个问题，不再需要重写RecyclerView。
