### ISSUE TITLE
viewpager 最内层放webview会滑动异常

### ISSUE THREAD

**Issue by LiuJQ** [YvesCheung/TouchEventBus#9]
RT

**Comment by YvesCheung** [comment]
我尝试复现以下= =，是指NestedScroll的例子里面 viewPager其中一个Fragment里面放webView吗

**Comment by LiuJQ** [comment]
> 我尝试复现以下= =，是指NestedScroll的例子里面 viewPager其中一个Fragment里面放webView吗

是的

**Comment by YvesCheung** [comment]
这个问题很好解决，根本原因是因为WebView没有遵从NestedScrolling机制，在网上找个实现了NestedScrollingChild接口的WebView换上去就可以： 例子实现 [3009e3e084ca6328dc5e8ae9ad4828797fc0ca6a]

**Comment by LiuJQ** [comment]
> 这个问题很好解决，根本原因是因为WebView没有遵从NestedScrolling机制，在网上找个实现了NestedScrollingChild接口的WebView换上去就可以： 例子实现 [[3009e3e](https://github.com/YvesCheung/TouchEventBus/commit/3009e3e084ca6328dc5e8ae9ad4828797fc0ca6a)]

是这么回事，thx
